### ISSUE TITLE
Fog color default value

### ISSUE THREAD

**Issue by ReidenXerx** [McJtyMods/LostWorlds#5]
[crash-2024-08-05_00.14.23-client.txt](https://github.com/user-attachments/files/16530804/crash-2024-08-05_00.14.23-client.txt)

steps for reproduce:
1. run server lost worlds + lost cities
2. foggy weather on server
3. try to log in from client
4. crash on client

**Comment by AlwaysReadyWBY** [comment]
have the same problem

**Comment by McJty** [comment]
It's fixed already. Update Lost Worlds
